name: PluginList
version: '${project.version}'
main: jp.yama2211.pllist.Main

commands:
  pluginlist:
    description: PluginlistSaveing

permissions:
  pllist.use:
    description: pluginlist Cmd Pex
    default: op